#!/usr/bin/env bash

P=$(dirname $0)
INPUT_MD="$1"
BASE_NAME="${1%*.*}"
TEMP_MD_WITH_CSS="${BASE_NAME}-with-css.md"
TEMP_HTML="${BASE_NAME}.html"
OUTPUT_PDF="${BASE_NAME}.pdf"

if [ ! -r "$INPUT_MD" ]
then
	echo >&2 "Usage: $(basename "$0") <file.markdown> [<optional.css>]"
	echo >&2 "       Creates file.html and file.pdf in the same folder"
	exit 1
fi

if [ -r "$2" ]
then
	echo '<style>' >"$TEMP_MD_WITH_CSS"
	cat "$2" >>"$TEMP_MD_WITH_CSS"
	echo '</style>' >>"$TEMP_MD_WITH_CSS"
	cat "$INPUT_MD" >>"$TEMP_MD_WITH_CSS"
else
	cp "$INPUT_MD" "$TEMP_MD_WITH_CSS"
fi

"$P/multimarkdown" --smart --notes --process-html -t html "$TEMP_MD_WITH_CSS" >"${TEMP_HTML}" && \
"$P/wkhtmltopdf" --outline --enable-local-file-access --enable-smart-shrinking "${TEMP_HTML}" "${OUTPUT_PDF}" && \
rm "$TEMP_MD_WITH_CSS"

