#!/usr/bin/env bash

P=$(dirname $0)
INPUT_MD="$1"
BASE_NAME="${1%*.*}"
TEMP_HTML="${BASE_NAME}.html"
OUTPUT_PDF="${BASE_NAME}.pdf"

if [ ! -r "$INPUT_MD" ]
then
	echo >&2 "Usage: $(basename "$0") <file.markdown> [<optional.css>]"
	echo >&2 "       Creates file.html and file.pdf in the same folder"
	exit 1
fi

cat >"$TEMP_HTML" <<EOT
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
$(cat "$P/default.css")
$(cat "$2" 2>/dev/null)
</style>
</head>
<body>
$("$P/multimarkdown" --smart --notes --process-html -t html "$INPUT_MD")
</body>
</html>
EOT

"$P/wkhtmltopdf" --outline --enable-local-file-access --enable-smart-shrinking "${TEMP_HTML}" "${OUTPUT_PDF}"

