#!/usr/bin/env bash
set -e
PREFIX="${HOME}/ffmpeg-prefix"
export PATH="${PREFIX}/bin:$PATH"
export DYLD_LIBRARY_PATH="${PREFIX}/lib"
export FREI0R_PATH="${PREFIX}/lib/frei0r-1"

nice -n 19 "${0##*/}" ${1+"$@"}

