#!/usr/bin/env bash
LIB="openssl"
VERSION="1.0.0e"
DEPEND="\
z:1.2.5 \
"
. "$(dirname $0)/common"

MD5="7040b89c4c58c7a1016c0dfa6e821c86"

echo "Downloading tarball"
http_fetch openssl-${VERSION}.tar.gz $MD5 \
"http://www.openssl.org/source/openssl-${VERSION}.tar.gz"

show_progress 2345 unpacking.log "Unpacking" \
<<< "tar xvz --strip-components 1 -f openssl-${VERSION}.tar.gz 2>&1"

sed -i '' -e 's#^);$#\
"ios","$ENV{CC}:-DTERMIOS::${BSDthreads}:::BN_LLONG RC2_CHAR RC4_INDEX DES_INT:${no_asm}:",\
);#' Configure


MAKE_OPTS="DIRS='crypto ssl engines' EXE='' SCRIPTS='' APPS='' MISC_APPS=''"
for arch in armv7 i386
do
	echo "Building $LIB for $arch"
	mkdir -p ".prefix/$arch"
	set_$arch
	show_progress 205 conf.log "    Configure" \
	<<< "./Configure \
--openssldir=$MY_TMP/.prefix/$arch \
threads \
zlib \
no-shared \
no-asm \
no-sse2 \
no-dso \
no-hw \
ios"

	show_progress 1286 build.log "    Build" \
	<<< "$MAKE $MAKE_OPTS"

	show_progress 281 install.log "    Install" \
	<<< "$MAKE $MAKE_OPTS install_sw"

	$MAKE clean >/dev/null 2>&1
done

echo -n "Creating fat libraries: "
for SLIB in crypto ssl
do
	xcrun -sdk iphoneos -r lipo -create -output "$PREFIX/lib/lib$SLIB.a" \
			 -arch armv7 ".prefix/armv7/lib/lib$SLIB.a" \
			 -arch i386  ".prefix/i386/lib/lib$SLIB.a"
done

ditto ".prefix/armv7/include" "$PREFIX/include"
