#!/usr/bin/env bash
LIB="bzip2"
VERSION="1.0.6"
. "$(dirname $0)/common"

MD5="00b516f4704d4a7cb50a1d97e6e8e15b"

msg "Downloading tarball"
http_fetch bzip2-${VERSION}.tar.gz $MD5 \
http://bzip.org/${VERSION}/bzip2-${VERSION}.tar.gz

msg "Unpacking"
tar xz --strip-components 1 -f bzip2-${VERSION}.tar.gz

for arch in armv7 armv7s arm64 i386
do
	msg "Building for $arch"
	set_$arch
    mkdir -p build/$arch
	$MAKE -d -s libbz2.a CC="$CC" AR="$AR" RANLIB="$RANLIB" CFLAGS="$CFLAGS -D_FILE_OFFSET_BITS=64" >>build/$arch/build.log
    mv libbz2.a build/$arch/
	$MAKE -s distclean >/dev/null
done

msg "Creating fat library"
xcrun -sdk iphoneos -r lipo -create -output "$PREFIX"/lib/libbz2.a \
-arch armv7  build/armv7/libbz2.a \
-arch armv7s build/armv7s/libbz2.a \
-arch arm64  build/arm64/libbz2.a \
-arch i386   build/i386/libbz2.a

msg "Copying header file"
cp bzlib.h "${PREFIX}/include/"

