#!/usr/bin/env bash
LIB="icu"
VERSION="4.8.1"
. "$(dirname $0)/common"

MD5=af36f635271a239d76d038d6cf8da8df

echo "Downloading tarball"
http_fetch icu4c-${VERSION//./_}-src.tgz $MD5 \
sourceforge:icu/ICU4C/$VERSION/icu4c-${VERSION//./_}-src.tgz

show_progress 3380 unpacking.log "Unpacking" \
<<< "tar xvz --strip-components 1 -f icu4c-${VERSION//./_}-src.tgz 2>&1"

cd source
# Remove some noise
sed -i -e 's/@echo "generating dependency.*$/#removed line/g' config/mh-darwin

ICU_DIR="$(pwd)"
cd "$ICU_DIR"

mkdir -p build/{macosx,armv7,i386} prefix

echo "Building ICU for MacOSX (needed for cross-compiling):"
export CC="${CCACHE}gcc"
export CXX="${CCACHE}g++"
cd "$ICU_DIR/build/macosx"
show_progress 174 conf.log "	Configure" \
<<< "$ICU_DIR/runConfigureICU MacOSX"
show_progress 3613 make.log "	Make" \
<<< "$MAKE"

CONFFLAGS="\
--disable-shared \
--enable-static \
--disable-renaming \
--disable-dyload \
--disable-tests \
--disable-samples \
--with-cross-build=$ICU_DIR/build/macosx \
"

for arch in armv7 i386
do
	echo "Building ICU for $arch"
	set_$arch
	export CFLAGS="$CFLAGS -DUCONFIG_NO_FILE_IO=1"
	export CXXFLAGS="$CXXFLAGS -DUCONFIG_NO_FILE_IO=1"
	cd "$ICU_DIR/build/$arch"
	show_progress 165 conf.log "	Configure" \
	<<< "$ICU_DIR/configure $CONFFLAGS --host=$HOST --prefix=$ICU_DIR/prefix/$arch"
	show_progress 3574 make.log "	Make" \
	<<< "$MAKE"
	show_progress 392 install.log "	Install" \
	<<< "$MAKE install"
	rm -rf "$ICU_DIR/build/$arch"
done

cd "$ICU_DIR/build"
echo -n "Creating fat library: "
for SLIB in icui18n icule icuuc icuio iculx icutu icudata
do
	lipo -create -output "$PREFIX/lib/lib$SLIB.a" \
		-arch armv7 "$ICU_DIR/prefix/armv7/lib/lib$SLIB.a" \
		-arch i386  "$ICU_DIR/prefix/i386/lib/lib$SLIB.a"
done
echo OK

show_progress 353 copy_headers.log "Copying headers" \
<<< "ditto $ICU_DIR/prefix/i386/include $PREFIX/include -V 2>&1"

