#!/usr/bin/env bash
LIB="protobuf"
VERSION="2.4.1"
DEPEND="\
z:1.2.5 \
"
. "$(dirname $0)/common"

MD5=ed436802019c9e1f40cc750eaf78f318

echo "Downloading tarball"
http_fetch protobuf-${VERSION}.tar.bz2 $MD5 \
http://protobuf.googlecode.com/files/protobuf-${VERSION}.tar.bz2

show_progress 580 unpacking.log "Unpacking" \
<<< "tar xvj --strip-components 1 -f protobuf-${VERSION}.tar.bz2 2>&1"

mkdir -p build/{macosx,armv7,i386}
ROOT_DIR="$(pwd)"

echo "Building protoc for MacOS X"
cd "$ROOT_DIR/build/macosx"
mkdir -p prefix
export CC="${CCACHE}gcc" CXX="${CCACHE}g++"
show_progress 242 conf.log "	Configure" \
<<< "$ROOT_DIR/configure --enable-static --disable-shared --prefix=$ROOT_DIR/build/macosx/prefix"
show_progress 213 build.log "	Build" \
<<< "$MAKE"
show_progress 59 install.log "	Install" \
<<< "$MAKE install"
mkdir -p "$PREFIX/bin"
cp "$ROOT_DIR/build/macosx/prefix/bin/protoc" "$PREFIX/bin"/
PROTOC="$PREFIX/bin/protoc"
echo "Installed in $PROTOC"
echo

for arch in armv7 i386
do
	echo "Building $LIB for $arch"
	set_$arch
	cd "$ROOT_DIR/build/$arch"
	mkdir -p prefix
	show_progress 256 conf.log "	Configure" \
	<<< "$ROOT_DIR/configure \
--host=$HOST \
--prefix=$ROOT_DIR/build/$arch/prefix \
--enable-static \
--disable-shared \
--with-protoc=$PROTOC"
	show_progress 217 build.log "	Build" \
	<<< "$MAKE"
	show_progress 67 install.log "	Install" \
	<<< "$MAKE install"
	echo
done

echo -n "Creating fat libraries: "
for SLIB in protobuf protobuf-lite protoc
do
	lipo -create -output "$PREFIX/lib/lib$SLIB.a" \
			 -arch armv7 "$ROOT_DIR/build/armv7/prefix/lib/lib$SLIB.a" \
			 -arch i386  "$ROOT_DIR/build/i386/prefix/lib/lib$SLIB.a"
done
echo OK

ditto "$ROOT_DIR/build/armv7/prefix/include" "$PREFIX/include"

