#!/usr/bin/env bash
LIB="re2"
# This should be set to the submit date of the commit below
VERSION="20110721.000000"
REV="7007b2180a421524eaf64392058111fc8950f4ac"
. "$(dirname $0)/common"

if ! hg clone -r $REV https://code.google.com/p/re2 >/dev/null 2>&1
then
	echo >&2 "Failed to clone [https://code.google.com/p/re2] into [$MY_TMP/re2]"
	exit 1
fi

cd re2

for arch in armv7 i386
do
	set_$arch
	$MAKE -s clean
	show_progress 27 ${arch}.log "Building for $arch" \
	<<< "$MAKE CC='$CC' AR='$AR' NM='$NM' CXXFLAGS='$CXXFLAGS' obj/libre2.a"
	mv obj/libre2.a "$PREFIX"/lib/libre2-${arch}.a
done

echo -n "Creating fat library... "
lipo -create -output "$PREFIX"/lib/libre2.a \
	-arch armv7 "$PREFIX"/lib/libre2-armv7.a \
	-arch i386  "$PREFIX"/lib/libre2-i386.a
rm "$PREFIX"/lib/libre2-{armv7,i386}.a
echo OK

echo -n "Moving headers into place... "
mkdir -p "$PREFIX"/include/re2
cp re2/{re2,set,stringpiece,variadic_function}.h "$PREFIX"/include/re2/
echo OK

