#!/usr/bin/env bash
LIB="bzip2"
VERSION="1.0.6"
. "$(dirname $0)/common"

MD5="00b516f4704d4a7cb50a1d97e6e8e15b"

msg "Downloading tarball"
http_fetch bzip2-${VERSION}.tar.gz $MD5 \
http://bzip.org/${VERSION}/bzip2-${VERSION}.tar.gz

msg "Unpacking"
tar xz --strip-components 1 -f bzip2-${VERSION}.tar.gz

for arch in armv7 i386
do
	msg "Building for $arch"
	set_$arch
	$MAKE -s clean >/dev/null
	$MAKE -s libbz2.a CC="$CC" AR="$AR" CFLAGS="$CFLAGS -D_FILE_OFFSET_BITS=64" >/dev/null
	mv libbz2.a libbz2-${arch}.a
done

msg "Creating fat library"
lipo -create -output "$PREFIX"/lib/libbz2.a \
         -arch armv7 libbz2-armv7.a \
         -arch i386  libbz2-i386.a

msg "Copying header file"
cp bzlib.h "${PREFIX}/include/"

