#!/usr/bin/env bash
LIB="zbar"
VERSION="20110823.191723"
REV="a111d70d612d"
. "$(dirname $0)/common"

MD5="9e16015deddaf7b978bd856ac46e7cf4"

if ! which autoreconf >/dev/null 2>/dev/null
then
	msg "Failed dependency: autoreconf"
	echo "Could not find autoreconf, which is needed to build $LIB. Please install it and try again. With MacPorts:"
	echo
	echo "	sudo port selfupdate"
	echo "	sudo port install autoconf"
	echo
	echo "...and ensure autoreconf is in your PATH"
	echo "Exiting..."
	exit 1
fi

echo "Downloading tarball"

http_fetch ${REV}.tar.bz2 $MD5 \
http://zbar.hg.sourceforge.net/hgweb/zbar/zbar/archive/${REV}.tar.bz2

show_progress 360 unpacking.log "Unpacking" \
<<< "tar xvj --strip-components 1 -f ${REV}.tar.bz2 2>&1"

show_progress 14 autoreconf.log "Generating configure script" \
<<< "autoreconf --install 2>&1"

for arch in armv7 i386
do
	echo "Building $LIB for $arch"
	mkdir -p "$MY_TMP/build/$arch/prefix"
	cd "$MY_TMP/build/$arch"
	set_$arch
	show_progress 231 conf.log "	Configure" \
	<<< "$MY_TMP/configure \
--host=$HOST \
--prefix=$MY_TMP/build/$arch/prefix \
--enable-static \
--disable-shared \
--disable-video \
--disable-rpath \
--without-imagemagick \
--without-qt \
--without-java \
--without-gtk \
--without-python \
--without-xv \
--without-xshm \
--without-x \
--without-jpeg \
--without-libiconv-prefix \
"
	show_progress 107 build.log "	Build" \
	<<< "$MAKE"
	show_progress 26 install.log "	Install" \
	<<< "$MAKE install"
	echo
done

echo -n "Creating fat libraries: "
lipo -create -output "$PREFIX/lib/libzbar.a" \
		 -arch armv7 "$MY_TMP/build/armv7/prefix/lib/libzbar.a" \
		 -arch i386  "$MY_TMP/build/i386/prefix/lib/libzbar.a"
echo OK

ditto "$MY_TMP/build/armv7/prefix/include" "$PREFIX/include"

