#!/usr/bin/env bash
set -e
if (($(git status --porcelain | wc -l)))
then
	echo >&2 "Working directory is dirty. First commit your stuff."
	exit 1
fi

if [ -z "$1" ]
then
	echo >&2 "Usage: git root-branch <root branch name>"
	exit 2
fi

git symbolic-ref HEAD "refs/heads/$1"
rm .git/index
git clean -fdx

