#!/usr/bin/env bash

ARCHIVE="/tmp/chrome-mac.zip"
TMPDIR="/tmp/nbc.$$"
LATEST=$1
if [ -z "$LATEST" ]
then
	LATEST=$(curl -L -s 'http://commondatastorage.googleapis.com/chromium-browser-continuous/Mac/LAST_CHANGE')
fi

echo "Downloading Chromium build ${LATEST}… "
[ -f "$ARCHIVE" ] && rm -rf "$ARCHIVE"
mkdir -p "$TMPDIR" && \
if curl -L "http://commondatastorage.googleapis.com/chromium-browser-continuous/Mac/${LATEST}/chrome-mac.zip" >"$ARCHIVE"
then
	echo -n "Installing… " && \
	ln -sf /Applications "$TMPDIR"/chrome-mac && \
	rm -rf /Applications/Chromium.app && \
	unzip "$ARCHIVE" -d "$TMPDIR" >/dev/null 2>&1 && \
	mv /Applications/Chromium.app/Contents/MacOS/Chromium /Applications/Chromium.app/Contents/MacOS/Chromium.real && \
	echo -e >/Applications/Chromium.app/Contents/MacOS/Chromium "#!/bin/bash\n\
cd /Applications/Chromium.app/Contents/MacOS && /Applications/Chromium.app/Contents/MacOS/Chromium.real --enable-webgl --enable-geolocation --allow-file-access-from-files --enable-internal-flash \$@" && \
	chmod 755 /Applications/Chromium.app/Contents/MacOS/Chromium && \
	echo 'OK' || echo 'FAILED'
fi
rm -rf "$ARCHIVE"
rm -rf "$TMPDIR"
