wget http://jaist.dl.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.3/OpenCV-2.4.3.tar.bz2
tar xf OpenCV-2.4.3.tar.bz2
cd OpenCV-2.4.3
cmake -G 'Unix Makefiles' \
"-DCMAKE_C_COMPILER=$GCC_FOR_CUDA" \
"-DCMAKE_CXX_COMPILER=$GXX_FOR_CUDA" \
-DCMAKE_VERBOSE=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
-DCMAKE_PREFIX_PATH:PATH="$PREFIX" \
-DCMAKE_INSTALL_PREFIX:PATH="$PREFIX" \
-DBUILD_NEW_PYTHON_SUPPORT=OFF \
-DBUILD_TESTS=OFF \
-DBUILD_PERF_TESTS=OFF \
-DBUILD_EXAMPLES=OFF \
-DBUILD_DOCS=OFF \
-DENABLE_PRECOMPILED_HEADERS=ON \
-DENABLE_FAST_MATH=ON \
-DENABLE_OMIT_FRAME_POINTER=ON \
-DENABLE_SSSE3=ON \
-DENABLE_SSE41=ON \
-DENABLE_SSE42=ON \
-DENABLE_AVX=ON \
-DWITH_FFMPEG=ON
make -j4 install
cd ..
rm -rf OpenCV-*

